### ISSUE TITLE
rembg dependency version error

### ISSUE THREAD

**Issue by gregorylearns** [danielgatis/docscan#3]
$ pip3 install docscan
yields this error

ERROR: Could not find a version that satisfies the requirement rembg==1.0.10 (from docscan) (from versions: 2.0.24)
ERROR: No matching distribution found for rembg==1.0.10 (from docscan)

Thank you

**Comment by SajjadIqbal-git** [comment]
same error I am facing. Any Solution?

**Comment by danielgatis** [comment]
fixed! ;)
try to install it again!
