### ISSUE TITLE
Conflicting Issue!

### ISSUE THREAD

**Issue by SajjadIqbal-git** [danielgatis/docscan#4]
The conflict is caused by:
    docscan 1.0.4 depends on rembg==1.0.10
    docscan 1.0.3 depends on rembg==1.0.9
    docscan 1.0.2 depends on rembg==1.0.7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

And I am not able to install the above version of rembg. @danielgatis  I think the old version rembg has been removed, yet docscan is not updated yet. Need solution for this!

**Comment by danielgatis** [comment]
fixed! ;)
try to install it again!
